export const temas = [
    "Noticias nacionales e internacionales",
    "Política y economía",
    "Medio ambiente y cambio climático",
    "Ciencia y tecnología",
    "Salud y bienestar",
    "Sociedad y cultura",
    "Entretenimiento",
    "Películas y series",
    "Música y conciertos",
    "Libros y literatura",
    "Videojuegos",
    "Arte y fotografía",
    "Viajes y turismo",
    "Deportes",
    "Fútbol",
    "Béisbol",
    "Baloncesto",
    "Tenis",
    "Atletismo",
    "Deportes olímpicos",
    "Aficiones",
    "Cocina y gastronomía",
    "Moda y belleza",
    "Jardinería y plantas",
    "Mascotas",
    "Manualidades y bricolaje",
    "Coleccionismo",
    "Desarrollo personal:",
    "Psicología y motivación",
    "Finanzas personales",
    "Emprendimiento",
    "Productividad",
    "Relaciones interpersonales",
    "Crecimiento espiritual",
]